name: Lint and Build
on:
  push:
    branches:
      - master
      - dev

jobs:
  lint and check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: check
        run: npm run check
  
  build:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and Push
        run: |
          echo "triggered by ${{ gitea.event_name }}"
          docker login ghcr.io -u "${{ secrets.ghcr_user }}" -p "${{ secrets.ghcr_token }}"
          docker build --pull -t "ghcr.io/rahn-it/website:${{ github.head_ref || github.ref_name }}" --squash .
          docker push "ghcr.io/rahn-it/website:${{ github.head_ref || github.ref_name }}"